### ISSUE TITLE
Merriweather typeface not compatible with XeLaTeX and LuaLaTeX in uureport

### ISSUE THREAD

**Issue by psyguy** [UtrechtUniversity/uucls#3] opened 2022-03-08 10:24 UTC
Hi,

I noticed that if you use Merriweather typeface in document class `uureport` (`\documentclass[english,merriweather]{uureport}`) and compile the document with either `XeLaTeX` or `LuaLaTeX`, the typesetting is distorted/crooked.

For instance, the following is the output when compiled with `pdfLaTeX`:

![image](https://user-images.githubusercontent.com/8527082/157216681-e7010761-d50b-440d-8095-e1466ea9743c.png)

And the following is the same part if the output when compiled with `XeLaTeX` and `LuaLaTeX`:

![image](https://user-images.githubusercontent.com/8527082/157216912-f2aa1525-db3c-489d-857e-6d832d372a73.png)

Note `a`s in the italicized (sub)subsections, as well as out of scale `x`s and `z`s and `v`s.

I assume it has nothing to do with the `cls`, though it might be worth mentioning in the repo readme.

**Comment by jkorb** [comment] 2022-03-15 15:28
Hi @psyguy ! Thanks for raising this issue. I'll need to investigate upstream (essentially the merriweather package) to see why the issue arises. It could turn out to be an incompatibility between `merriweather` and `XeLaTeX` and `LuaLaTex`. In that case, it seems the correct course of action would be to mention that in the readme as you say. I'll investigate and report back.

**Comment by jkorb** [comment] 2022-03-16 14:16
So, I've done some digging. The official `merriweather` package should work with `XeLaTex`, `LuaLaTex`, etc. (see https://ctan.org/pkg/merriweather). So the problem lies somewhere else. However, I was not able to reproduce the issue myself (working on vanilla Ubuntu 21.10 with just the necessary packages installed, i.e. `texlive`, `texlive-fonts-extra`, `texlive-lang-european` and `texlive-xetex` in this case). So I think the problem lies with your system rather than `merriweather` or `uucls`. May I ask what system you're working on?

**Comment by jkorb** [comment] 2022-03-24 08:39
Hi @psyguy , after some more testing it I still couldn't reproduce the problem. So, I'll be closing this issue for now. Feel free to re-open if you need any help figuring out what's going wrong on your system. In that case, it'd be great if you could let me know what kind of setup you're using: Windows, Mac, Linux (which version/distribution), which LaTeX install you're using (MiKTeX, MacTeX, or Overleaf in the browser), is there anything else that's loaded in your document (other packages, etc.), and so on. Cheers :)

**Closed by jkorb** 2022-03-24 08:39 UTC
Labels: needs-triage
